### ISSUE TITLE
Document / Add support for RESTenabled SQL

### ISSUE THREAD

**Issue by martindsouza** [martindsouza/docker-ords#10]
There's a few blog posts out there on ORDS REST enabled SQL. We should document / provide scripts on how to do it as APEX 18.1 allows for it.

Will be done as part of #20 as REST enabled SQL is required for SQL Dev Web

**Comment by cc13com** [comment]
Thanks for this idea. I tried something with this post [https://blogs.oracle.com/apex/get-started-with-rest-services-in-application-express-52-ea-1
](https://blogs.oracle.com/apex/get-started-with-rest-services-in-application-express-52-ea-1
) but it isn't working for me.

When I try to create the "Web Source Module" I receive the following message:

`An error occurred during URL invocation.

ORA-29024: Certificate validation failure`

<img width="802" alt="image" src="https://user-images.githubusercontent.com/35263232/52847711-3aa8fd00-310d-11e9-9e9c-a19d9223371d.png">

**Comment by martindsouza** [comment]
@cc13com Did you check if there's an HTTPS setting that could be causing this for you. It looks like it from the error message.

**Comment by martindsouza** [comment]
Done as part of #20
