### ISSUE TITLE
The pool named: |apex|pu| is invalid

### ISSUE THREAD

**Issue by omarsawalhah** [martindsouza/docker-ords#12]
I followed the steps to configure XE 18c, APEX and ORDS, when running the docker for the first time I am getting this error

WARNING: The pool named: |apex|pu| is invalid and will be ignored: The connection pool named: |apex|pu| is not correctly configured, due to the following error(s): IO Error: Unknown host specified 

Omar

**Comment by 4223** [comment]
I've got the same problem :( Didn't find any solution..

**Comment by martindsouza** [comment]
I was getting the same error but didn't affect me since I was referencing the `/ords/` url. What URL are you both accessing in the browser?

**Comment by 4223** [comment]
The URL I tried to access is the default APEX-URL on ORDS: http://127.0.0.1:32513/ords/f?p=4500
In the browser, I received a 500 (or 404, not quite 100% sure which one it was but can check later today if it's relevant) error message from ORDS.

**Comment by martindsouza** [comment]
Can you please do the following:
- Delete your current `ords` container
  - `docker stop ords`
  - `docker rm ords`
- Delete `ords` config:
  - `rm -rf ~/docker/ords/*`  (or where ever your config files are stored
- Run a new docker ORDS container (see this project for run script)
  - Copy the logs that you see outputted on the screen here 
  - Try to access `http://localhost:32513/ords` and copy some of the addition logs here.
- Stop the container
  - (either kill the process or run `docker stop ...`
- Run the container again and copy the logs
  - Can output the logs via `docker logs ords` (or your container name)

**Comment by 4223** [comment]
Thanks, will try it later today.

**Comment by 4223** [comment]
...that's the command I used after cleaning everything up according to your instructions:

```
docker run -it --rm   --network=oracle_network   -e TZ=Europe/Budapest   -e DB_HOSTNAME=oracle   -e DB_PORT=1521   -e DB_SERVICENAME=XEPDB1   -e APEX_PUBLIC_USER_PASS=Oracle18   -e APEX_LISTENER_PASS=Oracle18   -e APEX_REST_PASS=Oracle18   -e ORDS_PASS=Oracle18   -e SYS_PASS=Oracle18   --volume ~/docker/ords/ords-18.3.0/config:/opt/ords   --volume ~/software/docker/apex/18.2/images:/ords/apex-images   -p 32513:8080   ords:18.3.0
/opt/ords/defaults.xml not found. Installing ORDS
```
...and that's the resulting log:

```
Generating ords_params.properties
*** PARAMFILE: /ords/params/ords_params.properties
Nov 12, 2018 6:35:34 PM oracle.dbtools.rt.config.setup.SchemaSetup getInstallOrUpgrade
WARNING: Failed to connect to user ORDS_PUBLIC_USER jdbc:oracle:thin:@//oracle:1521/XEPDB1 
IO Error: Unknown host specified 
Nov 12, 2018 6:35:35 PM  
INFO: reloaded pools: []
2018-11-12 18:35:35.835:INFO::main: Logging initialized @9054ms to org.eclipse.jetty.util.log.StdErrLog
Nov 12, 2018 6:35:36 PM  
INFO: HTTP and HTTP/2 cleartext listening on port: 8080
Nov 12, 2018 6:35:36 PM  
INFO: Disabling document root because the specified folder does not exist: /opt/ords/standalone/doc_root
2018-11-12 18:35:36.970:INFO:oejs.Server:main: jetty-9.4.z-SNAPSHOT; built: 2018-05-03T15:56:21.710Z; git: daa59876e6f384329b122929e70a80934569428c; jvm 1.8.0_181-b13
2018-11-12 18:35:37.033:INFO:oejs.session:main: DefaultSessionIdManager workerName=node0
2018-11-12 18:35:37.034:INFO:oejs.session:main: No SessionScavenger set, using defaults
2018-11-12 18:35:37.037:INFO:oejs.session:main: node0 Scavenging every 660000ms
Nov 12, 2018 6:35:37 PM  
WARNING: The pool named: |apex|pu| is invalid and will be ignored: The connection pool named: |apex|pu| is not correctly configured, due to the following error(s): IO Error: Unknown host specified  
Nov 12, 2018 6:35:37 PM  
WARNING: The pool named: |apex|| is invalid and will be ignored: The connection pool named: |apex|| is not correctly configured, due to the following error(s): IO Error: Unknown host specified  
Nov 12, 2018 6:35:37 PM  
INFO: Oracle REST Data Services initialized
Oracle REST Data Services version : 18.3.0.r2701456
Oracle REST Data Services server info: jetty/9.4.z-SNAPSHOT

2018-11-12 18:35:37.666:INFO:oejsh.ContextHandler:main: Started o.e.j.s.ServletContextHandler@3712b94{/ords,null,AVAILABLE}
2018-11-12 18:35:37.667:INFO:oejsh.ContextHandler:main: Started o.e.j.s.h.ContextHandler@2833cc44{/i,null,AVAILABLE}
2018-11-12 18:35:37.695:INFO:oejs.AbstractConnector:main: Started ServerConnector@4d1b0d2a{HTTP/1.1,[http/1.1, h2c]}{0.0.0.0:8080}
2018-11-12 18:35:37.696:INFO:oejs.Server:main: Started @10915ms

```

**Comment by tensau** [comment]
@4223 upon reviewing your docker call, it's quite clear: the hostname (parameter DB_HOSTNAME) of the oracle-xe Docker container is "oracle-xe", and not "oracle" as in the script.
Changed it in my docker command, and it worked!

**Comment by martindsouza** [comment]
Closing since it's a Hostname issue.
