### ISSUE TITLE
404 no database

### ISSUE THREAD

**Issue by cc13com** [martindsouza/docker-ords#13]
Hello,

I thought I did it right, but it's not working for me.

Here are the code to build the container:

`docker run -it --rm \
  --network=oracle_network \
  -e TZ=America/Edmonton \
  -e DB_HOSTNAME=oracle-xe \
  -e DB_PORT=1521 \
  -e DB_SERVICENAME=orclpdb513.localdomain \
  -e APEX_PUBLIC_USER_PASS=oracle \
  -e APEX_LISTENER_PASS=oracle \
  -e APEX_REST_PASS=oracle \
  -e ORDS_PASS=oracle \
  -e SYS_PASS=Oradoc_db1 \
  --volume ~/docker/ords/ords-18.3.0/config:/opt/ords \
  --volume ~/docker/apex/5.1.3/images:/ords/apex-images \
  -p 32513:8080 \
  ords:18.3.0`

After clicking on the URL I see the following message:

`404 Not Found`

`Die Anforderung konnte keiner Datenbank zugeordnet werden. Stellen Sie sicher, dass die Anforderungs-URL richtig ist und dass Zuordnungen zwischen URL und Datenbank korrekt konfiguriert wurden`

Means the request cannot fulfill because there is no database assigned.

Best,
Carsten

**Comment by martindsouza** [comment]
@cc13com can you please verify your connections above (port, service name, host name, network, etc)?

**Comment by cc13com** [comment]
@martindsouza Hello, I'm not the docker pro, sorry.

I have started a oracle-xe container with the following settings:

<img width="409" alt="bildschirmfoto 2018-11-30 um 11 40 35" src="https://user-images.githubusercontent.com/35263232/49284396-c8713680-f494-11e8-8bd8-cae8c2ea3ce7.png">

<img width="859" alt="bildschirmfoto 2018-11-30 um 11 39 22" src="https://user-images.githubusercontent.com/35263232/49284357-a7a8e100-f494-11e8-89c4-8cdf7817a6d7.png">

And here are the settings for your docker-ords container:

<img width="860" alt="bildschirmfoto 2018-11-30 um 11 42 42" src="https://user-images.githubusercontent.com/35263232/49284507-16863a00-f495-11e8-893b-3415ab1381db.png">

<img width="588" alt="bildschirmfoto 2018-11-30 um 11 43 11" src="https://user-images.githubusercontent.com/35263232/49284528-243bbf80-f495-11e8-953f-28324ca2c14e.png">

<img width="414" alt="bildschirmfoto 2018-11-30 um 11 43 39" src="https://user-images.githubusercontent.com/35263232/49284555-374e8f80-f495-11e8-9a14-07719016a04b.png">

And the text when I start your container:

/opt/ords/defaults.xml found. Running standalone
2018-11-30 03:37:32.580:INFO::main: Logging initialized @2804ms to org.eclipse.jetty.util.log.StdErrLog
Nov 30, 2018 3:37:32 AM  
INFO: HTTP and HTTP/2 cleartext listening on port: 8080
Nov 30, 2018 3:37:32 AM  
INFO: Disabling document root because the specified folder does not exist: /opt/ords/standalone/doc_root
2018-11-30 03:37:33.676:INFO:oejs.Server:main: jetty-9.4.z-SNAPSHOT; built: 2018-05-03T15:56:21.710Z; git: daa59876e6f384329b122929e70a80934569428c; jvm 1.8.0_181-b13
2018-11-30 03:37:33.730:INFO:oejs.session:main: DefaultSessionIdManager workerName=node0
2018-11-30 03:37:33.731:INFO:oejs.session:main: No SessionScavenger set, using defaults
2018-11-30 03:37:33.738:INFO:oejs.session:main: node0 Scavenging every 660000ms
Nov 30, 2018 3:37:34 AM  
WARNING: The pool named: |apex|pu| is missing and will be ignored: The database service named: |apex|pu| does not exist
Nov 30, 2018 3:37:34 AM  
WARNING: The pool named: |apex|| is missing and will be ignored: The database service named: |apex|| does not exist
Nov 30, 2018 3:37:35 AM  
INFO: Oracle REST Data Services initialized
Oracle REST Data Services version : 18.3.0.r2701456
Oracle REST Data Services server info: jetty/9.4.z-SNAPSHOT

2018-11-30 03:37:35.078:INFO:oejsh.ContextHandler:main: Started o.e.j.s.ServletContextHandler@1b604f19{/ords,null,AVAILABLE}
2018-11-30 03:37:35.081:INFO:oejsh.ContextHandler:main: Started o.e.j.s.h.ContextHandler@7823a2f9{/i,null,AVAILABLE}
2018-11-30 03:37:35.121:INFO:oejs.AbstractConnector:main: Started ServerConnector@4e718207{HTTP/1.1,[http/1.1, h2c]}{0.0.0.0:8080}
2018-11-30 03:37:35.122:INFO:oejs.Server:main: Started @5349ms

If you need more information please give me a text.

Best,
Carsten
