### ISSUE TITLE
build

### ISSUE THREAD

**Issue by dobija** [martindsouza/docker-ords#16]
$ docker build -t ords:$ORDS_VERSION .
Sending build context to Docker daemon  60.36MB
Step 1/11 : FROM openjdk:8-jre-alpine
 ---> ce8477c7d086
Step 2/11 : MAINTAINER Martin DSouza <martin@talkapex.com>
 ---> Using cache
 ---> 06666e07acb0
Step 3/11 : ENV TZ="GMT"   APEX_CONFIG_DIR="/opt"   TOMCAT_HOME="/usr/local/tomcat"   APEX_PUBLIC_USER_NAME="APEX_PUBLIC_USER"   PLSQL_GATEWAY="true"   REST_SERVICES_APEX="false"   REST_SERVICES_ORDS="true"   MIGRATE_APEX_REST="true"   ORDS_DIR="/ords"
 ---> Using cache
 ---> 51cdfe925ba0
Step 4/11 : WORKDIR ${ORDS_DIR}
 ---> Using cache
 ---> 6f1a50a5b933
Step 5/11 : COPY ["ords.war", "scripts/*", "/tmp/"]
 ---> Using cache
 ---> 6278b12600c5
Step 6/11 : RUN chmod +x /tmp/docker-run.sh &&   /tmp/docker-run.sh
 ---> Running in 8d84c782653c
/bin/sh: /tmp/docker-run.sh: not found
The command '/bin/sh -c chmod +x /tmp/docker-run.sh &&   /tmp/docker-run.sh' returned a non-zero code: 127

**Comment by hg-smart** [comment]
hello martin, 
i experience the same issue
```
Step 5/11 : COPY ["ords.war", "scripts/*", "/tmp/"]
 ---> 5c02f6b71e59
Step 6/11 : RUN chmod +x /tmp/docker-run.sh &&   /tmp/docker-run.sh
 ---> Running in ad25a1c849d6
/bin/sh: /tmp/docker-run.sh: not found
The command '/bin/sh -c chmod +x /tmp/docker-run.sh &&   /tmp/docker-run.sh' returned a non-zero code: 127
```

Best Hansjörg

**Comment by Yah0000** [comment]
Hi, I had similar problem, but I found solution. 
Make sure that all off the scripts are saved in correct format line break.
I download git repo on Windows, send it to Linux and have same error. After changing line break to linux in Notepad++ Docker scripts runs fine.

**Comment by martindsouza** [comment]
All: Please use latest files for this project and see if it's still giving the same errors.

**Comment by martindsouza** [comment]
Closing since haven't hear any responses.
