### ISSUE TITLE
Memory Consumtion

### ISSUE THREAD

**Issue by Nicknag** [martindsouza/docker-ords#18]
Hi,
thanks for this image build. Works perfectly on my development server so far :)

But one thing that I recognized is that the memory consumption of the container is quiet high. It eats 650 MB when idle. Even the dockerized Oracle DB is only on 350 MB when idle.

Any clue it this is normal or can be tweaked somehow?

Thanks
Nick

**Comment by martindsouza** [comment]
@Nicknag are you talking about running memory (i.e. RAM)? I don't think I can do anything about that as it would be ORDS itself.

Note I've updated everything for 19.2. See if that helps.

**Comment by martindsouza** [comment]
@Nicknag closing this issue now as haven't heard a response for a while.
