### ISSUE TITLE
Typos in Readme

### ISSUE THREAD

**Issue by yachtsman60** [martindsouza/docker-ords#24]
Hi Martin,

Just following your instructions and cam across a couple of errors you may wish to edit in the Readme file.

`cd docker-ords (to cd docker-oracle-ords)`

`cp ~/Downloads/ords.*.zip files/ (to cp ~/Downloads/ords-*.zip files/)`

**Comment by martindsouza** [comment]
@yachtsman60 thanks for pointing these out. Just fixed
